version: '1.0'
services:

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - loki_data:/loki

    command: -config.file=/etc/loki/local-config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning # Путь к папке с настройками Grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true # Разрешаем анонимный доступ (для тестирования)
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # Даем анонимным пользователям права администратора
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml # Монтируем файл с настройками источников данных
      - grafana_data:/var/lib/grafana # Том для хранения данных Grafana (дашборды, настройки)
    depends_on:
      - loki
  main-service:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /app/logs
    depends_on:
      - redis
      - loki
    environment:
      - REDIS_URL=redis:6379
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  loki_data:
  grafana_data:
  redis_data: