auth_enabled: false # Отключаем аутентификацию для локальной разработки

server: # Настройка сервера Loki
  http_listen_port: 3100 # Порт, на котором слушает Loki

common: # Общие настройки
  instance_addr: 127.0.0.1 # Адрес instance
  path_prefix: /loki # Базовый путь для данных
  storage: 
    filesystem:
      chunks_directory: /loki/chunks # Папка для хранения чанков логов
      rules_directory: /loki/rules # Папка для правил
  replication_factor: 1 # Кол-во реплик данных (1 - без лепликации)
  ring: # Конфигурация кольца для распределенного режима
    kvstore:
      store: inmemory # Хранилище в памяти (для разработки)

limits_config: # Отключаем какие то метаданные т.к. докер ноет
  allow_structured_metadata: false

schema_config: # Конфигурация схемы хранения данных
  configs:
    - from: 2020-10-24 # Дата начала использования схема
      store: boltdb-shipper # тип индекса (boltdb легковесная встроенная бд для индексов / shipper  механизм для отправки индексов в обьектное хранилище (альтернатива tsdb))
      object_store: filesystem # тип хранилища (храним на локальном диске [gcs, s3, azure - альтернативы для прода])
      schema: v11 # версия схемы данных
      index:
        prefix: index_ # префикс для файлов индекса
        period: 24h # период ротации индекса

ruler: # настройка правил и алертинга
  alertmanager_url: http://localhost:9093 # куда отправляем аллерты